# system("
#     if [ #{ARGV[0]} = 'up' ]; then
#         echo '-----Check box-----'
#         ./install_box.sh
#         echo '-----Generate ssh keys-----'
#         ssh-keygen -f inception -q -N ""
#     fi
# ")

Vagrant.configure(2) do |config|
    # Образ виртуальной машины с Vagrant Cloud - по сабджекту CentOS
    config.vm.box = "centos/8"
    # The URL that the configured box can be found at
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"

    # Server
    # Имя виртуальной машины
    config.vm.define "hwoodwriS" do |server|
        # If set, Vagrant will update /etc/hosts on the guest with the configured hostname
        server.vm.hostname = "hwoodwriS"
        # Настройка сети на виртуальной машине
        server.vm.network "private_network", ip: "192.168.42.110"
        # Настройки виртуальной машины и выбор провайдера
        server.vm.provider "virtualbox" do |v|
            # Changes the VM's name
            v.customize ["modifyvm", :id, "--name", "hwoodwriS"]
            # Makes the NAT engine proxy all guest DNS requests to the host's DNS servers
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            # Makes the NAT engine use the host's resolver mechanisms to handle DNS requests
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            # 1 Гб оперативной памяти
            v.memory = "1024"
            # Одноядерный процессор
            v.cpus = 1
        end
        #
#         server.vm.provision "file", source: "./inception.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
#         server.vm.provision "file", source: "./inception", destination: "/home/vagrant/.ssh/id_rsa"
        # Команда, которая выполнится после создания машины
        server.vm.provision "shell", run: "always", path: "./install_server.sh"
    end

    # ServerWorker
    config.vm.define "hwoodwriSW" do |agent|
        agent.vm.hostname = "hwoodwriSW"
        agent.vm.network "private_network", ip: "192.168.42.111"
        agent.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "hwoodwriSW"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.memory = "1024"
            v.cpus = 1
        end
    agent.vm.provision "shell", run: "always", path: "./install_serverworker.sh"
#     config.vm.provision "shell", inline: <<-SHELL
#     SHELL
#         agent.vm.provision "shell", path: "./install_serverworker.sh"
    end

end