Vagrant.configure(2) do |config|
    # Образ виртуальной машины с Vagrant Cloud - по сабжекту CentOS
    config.vm.box = "centos8"
    # The URL that the configured box can be found at.
    config.vm.box_url =

    # Server
    config.vm.define "hwoodwriS" do |control|
        control.vm.hostname = "hwoodwriS"
        control.vm.network REDACTED, ip: "192.168.42.110"
        control.vm.provider REDACTED do |v|
            v.customize ["modifyvm", :id, "--name", "hwoodwriS"]
        [...]
        end
    config.vm.provision :shell, :inline => SHELL
    [...]
    SHELL
    control.vm.provision "shell", path: REDACTED
    end

    # ServerWorker
    config.vm.define "hwoodwriSW" do |control|
       control.vm.hostname = "hwoodwriS"
        control.vm.network REDACTED, ip: "192.168.42.111"
        control.vm.provider REDACTED do |v|
            v.customize ["modifyvm", :id, "--name", "hwoodwriSW"]
        [...]
        end
    config.vm.provision "shell", inline: <<-SHELL
    [..]
    SHELL
    control.vm.provision "shell", path: REDACTED
    end
end