system("
    if [ #{ARGV[0]} = 'up' ]; then
        ./scripts/ssh_gen.sh
    fi
")

Vagrant.configure(2) do |config|
    config.vm.box = "centos/stream8"
    config.vm.box_version = "20210210.0"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/stream8"

    config.vm.define "p3" do |server|
        server.vm.hostname = "p3"
        server.vm.network "private_network", ip: "192.168.42.110"
        server.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "p3"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.memory = 8192
        v.cpus = 4
        end

        server.vm.provision "file", source: "./key.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        server.vm.provision "file", source: "./key", destination: "/home/vagrant/.ssh/id_rsa"
        server.vm.provision "file", source: "./scripts/init.sh", destination: "/home/vagrant/init.sh"
        server.vm.provision "file", source: "./scripts/start.sh", destination: "/home/vagrant/start.sh"
        server.vm.provision "file", source: "./confs/application.yaml", destination: "/home/vagrant/application.yaml"
    end
end